//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeoMagGUI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GeoMagGUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ApplicationPreferences.json.
        /// </summary>
        internal static string File_Name_Application_Preferences_JSON {
            get {
                return ResourceManager.GetString("File_Name_Application_Preferences_JSON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MagneticModels.json.
        /// </summary>
        internal static string File_Name_Magnetic_Model_JSON {
            get {
                return ResourceManager.GetString("File_Name_Magnetic_Model_JSON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Supported Coefficient Files (*.cof;*.dat)|*.cof;*.dat.
        /// </summary>
        internal static string File_Type_All_Coeff_Files {
            get {
                return ResourceManager.GetString("File_Type_All_Coeff_Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text File  (Tab delimited) (*.txt)|*.txt.
        /// </summary>
        internal static string File_Type_Text_Tab {
            get {
                return ResourceManager.GetString("File_Type_Text_Tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to assets.
        /// </summary>
        internal static string Folder_Assets {
            get {
                return ResourceManager.GetString("Folder_Assets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to coefficient.
        /// </summary>
        internal static string Folder_Coeffient {
            get {
                return ResourceManager.GetString("Folder_Coeffient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to documentation.
        /// </summary>
        internal static string Folder_Documentation {
            get {
                return ResourceManager.GetString("Folder_Documentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] IGRF12 {
            get {
                object obj = ResourceManager.GetObject("IGRF12", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] LICENSE {
            get {
                object obj = ResourceManager.GetObject("LICENSE", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Location_icon_16 {
            get {
                object obj = ResourceManager.GetObject("Location_icon_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Magnet {
            get {
                object obj = ResourceManager.GetObject("Magnet", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] README {
            get {
                object obj = ResourceManager.GetObject("README", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] WMM2015 {
            get {
                object obj = ResourceManager.GetObject("WMM2015", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
