<#
.SYNOPSIS
    Generates WiX file components from the build output directory.

.DESCRIPTION
    This script scans the build output directory and generates a WiX source file
    containing component definitions for all application files (excluding subdirectories
    which are handled separately in Product.wxs).

.PARAMETER BuildOutputPath
    The path to the build output directory (e.g., GeoMagGUI\bin\Release)

.PARAMETER Version
    The version number for the build

.EXAMPLE
    .\Generate-FileComponents.ps1 -BuildOutputPath "GeoMagGUI\bin\Release" -Version "1.5.0.0"
#>

param(
    [Parameter(Mandatory=$true)]
    [string]$BuildOutputPath,

    [Parameter(Mandatory=$true)]
    [string]$Version
)

# Ensure the build output path exists
if (-not (Test-Path $BuildOutputPath)) {
    Write-Error "Build output path not found: $BuildOutputPath"
    exit 1
}

# Get the absolute path
$BuildOutputPath = Resolve-Path $BuildOutputPath

# Define files to exclude (these are handled separately or not needed)
$excludePatterns = @(
    "*.pdb",
    "*.xml",
    "*.config.transform"
)

# Define directories to exclude (handled separately in Product.wxs)
$excludeDirectories = @(
    "coefficient",
    "documentation"
)

# Get all files in the root of the build output (not subdirectories)
$files = Get-ChildItem -Path $BuildOutputPath -File | Where-Object {
    $exclude = $false
    foreach ($pattern in $excludePatterns) {
        if ($_.Name -like $pattern) {
            $exclude = $true
            break
        }
    }
    -not $exclude
}

# Generate unique component GUIDs based on file names
function Get-DeterministicGuid {
    param([string]$seed)
    $md5 = [System.Security.Cryptography.MD5]::Create()
    $bytes = [System.Text.Encoding]::UTF8.GetBytes($seed)
    $hash = $md5.ComputeHash($bytes)
    return [Guid]::new($hash).ToString().ToUpper()
}

# Start building the WiX source
$wxsContent = @"
<?xml version="1.0" encoding="UTF-8"?>
<!-- This file is auto-generated by Generate-FileComponents.ps1 -->
<Wix xmlns="http://wixtoolset.org/schemas/v4/wxs">
  <Fragment>
    <ComponentGroup Id="ProductComponents" Directory="INSTALLFOLDER">
"@

foreach ($file in $files) {
    $componentId = "Component_" + ($file.Name -replace '[^a-zA-Z0-9]', '_')
    $fileId = "File_" + ($file.Name -replace '[^a-zA-Z0-9]', '_')
    $guid = Get-DeterministicGuid -seed "GeoMagSharp_$($file.Name)"

    $wxsContent += @"

      <Component Id="$componentId" Guid="$guid">
        <File Id="$fileId" Source="`$(var.BuildOutput)\$($file.Name)" KeyPath="yes" />
      </Component>
"@
}

$wxsContent += @"

    </ComponentGroup>
  </Fragment>
</Wix>
"@

# Write the output file
$outputPath = Join-Path (Split-Path $MyInvocation.MyCommand.Path -Parent) "FileComponents.wxs"
$wxsContent | Out-File -FilePath $outputPath -Encoding UTF8

Write-Host "Generated WiX components file: $outputPath"
Write-Host "Included $($files.Count) files"
